"""empty message

Revision ID: 169a416c1322
Revises: 
Create Date: 2023-07-14 04:52:54.255309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169a416c1322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tes',
    sa.Column('id_employee', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id_employee')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tes')
    # ### end Alembic commands ###
